### ISSUE TITLE
Plugin doesen't work

### ISSUE THREAD

**Issue by m0bYczE** [XvitrixCZE/Annihilation#2]
Hello, I have your plugin on spigot version 1.8.8 a plugin has very errors.
Plugin version is 2.1.1.
Can you fix it? 

Thx.

**Comment by samueldon720** [comment]
same problem i go on server and i type in /annihilation and nothing happens

**Comment by m0bYczE** [comment]
How version plugin and server use ?

**Comment by samueldon720** [comment]
Anni 2.1.1 bukkit server its 1.8.6

**Comment by XvitrixCZE** [comment]
Oh, I fixed it in Anni2.2, but I'm working on better update...

**Comment by samueldon720** [comment]
Yay!
