### ISSUE TITLE
Bungee

### ISSUE THREAD

**Issue by majovec** [XvitrixCZE/Annihilation#4]
Plugin je podporovan jen na bungee ?

**Comment by XvitrixCZE** [comment]
Ne, ale platí, že je pouze 1 aréna na 1 server.

**Comment by majovec** [comment]
kamo diky ze po takove době se ozivas uz nepotrebuji ale kdyby si se chtěl kouknout na gameteam PE anni pl tak na mem profilu pod tajnou myska věci

**Comment by XvitrixCZE** [comment]
Tak pardon, na GitHub jsem extrémně dlouho nezavítal.
